### ISSUE TITLE
hp мобов бразилии

### ISSUE THREAD

**Issue by Manyaka** [FreeRO/calc#9]
Iara   (IARA)   Mob-ID#2069 - http://ratemyserver.net/index.php?mob_name=iara&page=mob_db&f=1&mob_search=Search - 5890 => в кальке 18952

Piranha   (PIRANHA)   Mob-ID#2070 - http://ratemyserver.net/index.php?mob_name=piranha&page=mob_db&f=1&mob_search=Search - 4522 => в кальке 15882

На bra_fild01 тоже hp не соответствует.

Причем, в игре то нормальное количество hp.

**Comment by mr-ekkusu** [comment]
Исправлено в #13. Спасибо, @TheKnight =)
